// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/transaction.proto

package transactionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveTransactionRequest) Reset() {
	*x = ReserveTransactionRequest{}
	mi := &file_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveTransactionRequest) ProtoMessage() {}

func (x *ReserveTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveTransactionRequest.ProtoReflect.Descriptor instead.
func (*ReserveTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ReserveTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReserveTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveTransactionResponse) Reset() {
	*x = ReserveTransactionResponse{}
	mi := &file_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveTransactionResponse) ProtoMessage() {}

func (x *ReserveTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveTransactionResponse.ProtoReflect.Descriptor instead.
func (*ReserveTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveTransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_transaction_proto protoreflect.FileDescriptor

const file_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x17proto/transaction.proto\x12\vtransaction\"Z\n" +
	"\x19ReserveTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"4\n" +
	"\x1aReserveTransactionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2{\n" +
	"\x12TransactionService\x12e\n" +
	"\x12ReserveTransaction\x12&.transaction.ReserveTransactionRequest\x1a'.transaction.ReserveTransactionResponseBWZUgithub.com/Ephraimdebel/transaction-switch/internal/transaction/api/gen/transactionpbb\x06proto3"

var (
	file_proto_transaction_proto_rawDescOnce sync.Once
	file_proto_transaction_proto_rawDescData []byte
)

func file_proto_transaction_proto_rawDescGZIP() []byte {
	file_proto_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_proto_rawDesc), len(file_proto_transaction_proto_rawDesc)))
	})
	return file_proto_transaction_proto_rawDescData
}

var file_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_transaction_proto_goTypes = []any{
	(*ReserveTransactionRequest)(nil),  // 0: transaction.ReserveTransactionRequest
	(*ReserveTransactionResponse)(nil), // 1: transaction.ReserveTransactionResponse
}
var file_proto_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.TransactionService.ReserveTransaction:input_type -> transaction.ReserveTransactionRequest
	1, // 1: transaction.TransactionService.ReserveTransaction:output_type -> transaction.ReserveTransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_transaction_proto_init() }
func file_proto_transaction_proto_init() {
	if File_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_proto_rawDesc), len(file_proto_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transaction_proto_depIdxs,
		MessageInfos:      file_proto_transaction_proto_msgTypes,
	}.Build()
	File_proto_transaction_proto = out.File
	file_proto_transaction_proto_goTypes = nil
	file_proto_transaction_proto_depIdxs = nil
}
